### PR TITLE
Updated App icons

### PR DESCRIPTION
**Pull request by anshumandubey**
Fixes #64 
Issue #17 
Description

App icons changed to the given guidelines 

BEFORE: 
image
image

AFTER: 
ic_launcher_round
ic_launcher

Other changes:
None

### CODE REVIEW

**Comment by thayumaanavan** [comment]
@anshumandubey  Please update the PR description as per [PR template](https://github.com/UdacityAndroidDevScholarship/quiz-app/blob/master/docs/pull_request_template.md)

**Comment by anshumandubey** [comment]
Done 😄

**Comment by sagarsrao** [comment]
Nice work @anshumandubey.

**Comment by anshumandubey** [comment]
Thank You :)

**Comment by aditisoni8899** [comment]
@anshumandubey Thank you for your contribution. Your logo is also among most suitable logos for the App. But as a team based decision, we are merging the best logo among all the PRs. You did a great job keep up all the good work. Closing this PR. Looking forward to some more contribution from your side.

**Pull request closed without merging**
