### PR TITLE
Added login screen UI

### LINKED ISSUE #18: Login screen UI
Complete by: 16-April-2018, EOD

- Only Google Login (Only UI)
- No mockup. Only implementation (XML Layout)

**Note**: App's color scheme will be decided based on the best UI implementation.

Sample UI Mockup : https://drive.google.com/open?id=1kCM_axXbQkgSOD7iAhxI0gCaxMQ_OdVl

### PR DESCRIPTION
**Pull request by Jap-Leen**
Fixes #18 

## Description

Added the login screen UI.

### CODE REVIEW

**Comment by drulabs** [comment]
Hey @Jap-Leen, please include screenshot of the login UI. here in comments (not in the repo)

**Comment by drulabs** [comment]
Also. Request you to follow the Pull Request template that is setup. Please see this for sample https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/25

**Comment by aditisoni8899** [comment]
Closing this PR as you have not followed our PR template. We had also requested you to provide a screenshot in the slack DM but no response from your side.

**Comment by thayumaanavan** [comment]
@Jap-Leen  No issues. You can check on the open issues and work on it.

**Pull request closed without merging**
