### PR TITLE
Issue#83 Feature-store notification

### LINKED ISSUE #83: Store Notifications
**Finish by Tuesday, 02-May-2018**

1. Create methods in DBHandler to add a notification, to retrieve all notifications and search by text. Search in title and description. Use the `db` object in `DBHandler`.
Method signatures: 
- `addNotification(Notification notification)`
- `List<Notification> getAllNotifications(int startFrom, int limit)`
- `List<Notification> searchNotifications(String query, int startFrom, int limit)`

Ignore the `startFrom` and `limit` parameter for now. Search should be performed in `title` and `description` field of notification table.

Add signatures all the above methods in DataHandler too. Implement these methods in `AppDataHandler` and use the instance of `DBHandler` in the class to save notifications.

2. Private method in `services/FBMessagingService`->`storeNotification(RemoteMessage)` It should extract data from `RemoteMessage.getData()`, create a `models/Notification` Object and save it using `DataHandlerProvider.provide().saveNotification(...)`

Remote Message Payload defined in #82

### PR DESCRIPTION
**Pull request by rahul7838**
Fixes #83 

## Description

Made the changes as advice and also implemented the 2nd point of this issue#83

### CODE REVIEW

**Comment by drulabs** [comment]
FYI. You don't have to raise a new PR. Just commit your changes in the same local branch `feature-store_notification1`.

**Comment by drulabs** [comment]
@rahul7838 Thanks for making the changes. It looks great. Will update you after the deadline for the issue. Appreciate your time and efforts in adding this feature.

**Comment by rahul7838** [comment]
@drulabs  Thanks for the appreciation. Looking forward to work on notification activity.

**Comment by drulabs** [comment]
@rahul7838 you are in luck. There is already a ticket for UI of notification activity. [Here](https://github.com/UdacityAndroidDevScholarship/quiz-app/issues/75).

**Comment by aditisoni8899** [comment]
Approved by Kaushal and Vansh.

**Comment by drulabs** [comment]
@rahul7838 please provide your slack handle

**Comment by rahul7838** [comment]
@drulabs My slack handle is rs_03(Rahul Singhal)

**Pull request merged**
