### PR TITLE
SignIn UI Fix

### PR DESCRIPTION
**Pull request by pjoshi08**
Fixes #SignIn UI

## Description

Fixed a bug where the loading animation was overlapped by the sign in button. Also, changed the Intro text.

## Screenshots

**BEFORE**:
signin_before

**AFTER**:
signin_after

## Other changes (e.g. bug fixes, UI tweaks, refactors)

Fixed hard coded dimension values.

### CODE REVIEW

**Comment by CoderVishalSehgal** [comment]
@pjoshi08 The UI needs to improve and replace the logo with the quiz-app logo.

**Comment by pjoshi08** [comment]
@CoderVishalSehgal The UI improvement part should be done as part of a different issue/PR. The same goes for quiz app logo.
@drulabs Please have a look.

**Comment by drulabs** [comment]
@CoderVishalSehgal sure I will replace the logo. But we are planning a release today, UI improvements can be part of next release.

**Review by drulabs — APPROVED** [review]

**Comment by hilalsaim** [comment]
Hi, I'm not logged in with the google API. I created the JKS file. I took the Sha1 code. I am trying to connect to my own FireBase, but not logging in. What should I do? Can you help me?

**Pull request merged**
