### PR TITLE
Add filtering drop-down on Home screen

### LINKED ISSUE #79: UI/UX Enhancement: Add filtering drop-down on Home screen.
**Complete By : 30th April 2018, EOD.**

*Requirements:*
- Remove the current toggle button(unattempted)
- Add these *Filtering* options :
   A) All
   B) Attempted
   C) Un-attempted
   D) Bookmarks.
- The menu *slides down* from the toolbar and after selecting an option it *slides up* again.

**Sample UI**
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#home-screen-list-filterdrop-down

**Note:** We have added a color palette on our wiki page for reference to maintain consistency throughout the app screens. Please use it for future contributions.

### PR DESCRIPTION
**Pull request by bnayagrawal**
Fixes #79 

## Description

_Removed the previous toggle button and replaced with an ImageButton. Added four quiz filter options as radio buttons. When the ImageButton(Quiz filter view toggle) is clicked a viewHolder containing the four quiz filter radio buttons will slide down. After choosing a quiz filter user can click on the  ImageButton(Quiz filter view toggle)  again to hide(ViewHolder will slide up) the view._

## Before & After Screenshots

**BEFORE**:
Screenshot before

**AFTER**:

## Other changes (e.g. bug fixes, UI tweaks, refactors)

_No other changes performed._

### CODE REVIEW

**Comment by drulabs** [comment]
@bnayagrawal There were some new conflicts in your PR due to some recent changes. I've resolved those.

**Comment by bnayagrawal** [comment]
Thank you @drulabs

**Comment by aditisoni8899** [comment]
@bnayagrawal Thank you for the contribution. We have found your PR as the most suitable among all. But we are concerned about many little things and need clarifications from your side.

- In the code, remove hardcoded dimensions and color codes and add them to the res/dimens.xml and res/colors.xml file.

*Note* - Need your action on this ASAP.

**Comment by bnayagrawal** [comment]
@aditisoni8899 whatever lines of code I have added doesn't contain any hard coded string, dimension or color codes. I have already added them to strings.XML, dimens.XML and colors.XML
. There were hard coded values when I have forked this repo. So I haven't modified them as I haven't wrote those lines of code. Thank you.

**Comment by bnayagrawal** [comment]
Thank you @drulabs

**Comment by vansh1sh** [comment]
Approved. Nice work @bnayagrawal

**Pull request merged**
