### PR TITLE
Feature login screen UI

### PR DESCRIPTION
**Pull request by derrickabreo**
## Description

Added Login/SignIn Screen(no Java file) 

**AFTER**:
login_screen

## Other changes.

1. Added Udacity logo as a drawable.
2. Added Roboto Fonts (Thinand Medium).
3. Added String Values required to create Login Screen (1 String Value).
4. Commented two lines in introActivity.java which were not require.
5. Used Primary color for background  and Udacity logo.

### CODE REVIEW

**Comment by drulabs** [comment]
@derrickabreo Please resolve the conflicts. This PR can't be merged right now

**Comment by derrickabreo** [comment]
@drulabs I am trying to resolve the conflict.

**Comment by drulabs** [comment]
This PR still has conflicts. Just before raising the PR see if the "can be merged automatically" message is displayed. You don't have to close and reopen the PR. Just do an upstream git fetch from development branch.

**Comment by derrickabreo** [comment]
@drulabs Thanks. Fixed it.

**Comment by vansh1sh** [comment]
@derrickabreo Thankyou for the contribution. We appreciate your work. As a team decision based on votes, we are merging this PR with the branch.

Looking forward to some more contributions from your side.

**Pull request merged**
