### PR TITLE
discussion screen ui, presenter, view added

### LINKED ISSUE #103: Quiz Discussion Screen
**Complete By: 7th May 2018 EOD**

This is the Discussion Screen UI for contacting quiz creators and community members and asking them for any help and open discussion regarding Quiz.

1. follow the design, see *home* package for the sample. 
2. Create Contract which must contain Presenter and View interfaces. Make the Activity implement this **View** interface.
3. create a package  **...ui/discussion** and add all these files.
4. Layout wise create an `item_discussion.xml` and `activity_quiz_discussion.xml`. Use any layout you find suitable and use `recyclerview` inside it.
5. Create a recycler view adapter that supports additions of `models/Comment` items.

**UI Requirements:**

* It contains a RecyclerView.
* RecyclerView item should contain a profile picture, name, time.
* Chat bubble with description text.
* EditText and send button just like Whatsapp. 

**Sample UI link**: https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#quiz-discussion-activity

### PR DESCRIPTION
**Pull request by mdrahil**
Fixes #103 

## Description

I have implemented the Discussion Screen UI, added Presenter and View also. For now, on clicking home screen quiz items it will navigate to the Help/ Discussion Screen. The discussion screen has only dummy items for now.  Once the "load comments and add comment" API will be available from the data layer there are some todo items those need to be implemented. For now please focus on UI only.

## Screenshots

**AFTER**:

image

## Other changes 
added integer.xml in values added some strings and dimens in values, added some assets in drawable folder.

### CODE REVIEW

**Comment by drulabs** [comment]
@mdrahil this looks great. You have not only implemented the UI but you have followed the current design and created presenter. Awesome work. Even if we select someone else's UI, we will use the presenter and adapter in this PR. Thanks for your contribution.

**Comment by mdrahil** [comment]
@drulabs thank you for nice comments.

**Comment by aditisoni8899** [comment]
@kdhruw Now there is conflict please resolve.

**Comment by drulabs** [comment]
@aditisoni8899 resolving it now. Please tag @drulabs (personal git handle) not @kdhruw.

**Comment by aditisoni8899** [comment]
Resolved @drulabs Have a look

**Comment by drulabs** [comment]
Looks good @aditisoni8899

**Comment by aditisoni8899** [comment]
Merging this PR @drulabs

**Pull request merged**
