### PR TITLE
Updated UI in Login Screen.

### PR DESCRIPTION
**Pull request by AjaySharvesh3**
capture

### CODE REVIEW

**Comment by drulabs** [comment]
@AjaySharvesh3 make sure there are no conflicts. Right now this PR can't be merged.

**Comment by AjaySharvesh3** [comment]
@drulabs Resolved Conflicts.

**Comment by aditisoni8899** [comment]
@AjaySharvesh3 Thank you for the contribution. We appreciate your work. As a team decision based on the votes, there could have been a better UI design based on the following:
- Logos and text are not visible properly
- More creativity required
- Should follow the material design

We're closing this PR. Looking forward to some more contributions from your side.

**Comment by aditisoni8899** [comment]
@AjaySharvesh3  Thank you for the contribution. We appreciate your work. As a team decision based on the votes, there could have been a better UI design based on the following:

- Logos and text are not visible properly
- More creativity required
- Should follow the material design

We're closing this PR. Looking forward to some more contributions from your side.

**Pull request closed without merging**
