### PR TITLE
Added Settings Activity along with settingsFragment and customDialog …

### PR DESCRIPTION
**Pull request by imashwani**
Added Settings Activity along with settingsFragment and customDialog layout

Added files:
	SettingsActivity.java
	SettingsFragment.java
	Activity_settings.xml
	Preference_screen.xml
	Custom_dialog_signout.xml
Made changes to following file
	AndroidManifest.xml : added gradle support for preference v7
	arrays.xml : added 2 string-array for theme preference list 
	strings.xml : added set of value and labels for preference fragment

I have fulfilled all the requirements for this issue, if something is missing let me know.
This is my first commit.
Thankyou for your attention.

### CODE REVIEW

**Comment by imashwani** [comment]
Solved issue #105 here in this commit

**Comment by vansh1sh** [comment]
@imashwani Your work looks good, although you have added a different version of constraint layout as well. Please remove that. Also, please resolve the branch conflicts.

**Comment by imashwani** [comment]
thankyou for reviewing the code, i will make the required changes within an hour and push the changes asap.

**Comment by imashwani** [comment]
i have made the changes and created a new PR #142 . please look into that and if it is ok merge it please.

**Comment by vansh1sh** [comment]
Closing this PR according to the comments above.

**Pull request closed without merging**
