### PR TITLE
Feature details page UI

### LINKED ISSUE #19: Get Details Page UI
Complete by: 19 April 2018 EOD.

- It is a one time screen after a user authenticates. 

The fields should include:
- Name
- Photo (Use an image from your google account OR select an avatar from a list)
- Slack Handle
- Select your track spinner.
- Email (Not editable, only Text view)
- Submit/Next Button

A sample UI :

### PR DESCRIPTION
**Pull request by derrickabreo**
Fixes #19 

## Description

_Implemented Details page UI with no Java code_

## Before & After Screenshots
**AFTER**

**BEFORE**:

## Other changes 

1. Added new XML resource file for Details Page UI.
2. Added new fonts (Roboto variants)
3. Added strings values corresponding to details page UI.
4. Added new colors in colors.xml
5. Created a new drawable file for the details layout background. 
6. Added few icons for the UI.

### CODE REVIEW

**Comment by derrickabreo** [comment]
I have made requested changes. Please review.

**Comment by derrickabreo** [comment]
Fixed the conflicts

**Comment by derrickabreo** [comment]
Fixed the conflicts. Please Review the changes.

**Comment by derrickabreo** [comment]
@aditisoni8899 I'll fix the issues ASAP.

**Comment by aditisoni8899** [comment]
@derrickabreo If you can do it by today, it will be great.

**Comment by derrickabreo** [comment]
@aditisoni8899 Sure. I Update it by EOD.

**Comment by derrickabreo** [comment]
@aditisoni8899 I have changed the size of the gray portion. Please check.

**Comment by drulabs** [comment]
@derrickabreo you have removed the git conflicts `<<<<<<< HEAD, >>>>>> upstream / development` etc. Please do not commit files that contians these conflict texts.

**Comment by derrickabreo** [comment]
@drulabs I have removed intro_screen_two.xml but I need help with Squash and DBHelper.

**Comment by drulabs** [comment]
@derrickabreo thanks for making the changes. I am approving the changes, lets connect on slack for other queries.

**Pull request merged**
