### PR TITLE
Implemented Settings Activity as per requirements

### LINKED ISSUE #105: Settings Activity
**Complete By: 8th May 2018 EOD**

This is the settings activity of the QuizApp and it contains some basic settings.

**Requirements:**
* It must contain three items, check out the sample UI.
* Create a **SettingsActivity.java**.
* Create a *settings_app.xml* inside the *res/xml* folder and add the **PreferenceScreen** inside that activity and the respective items as shown in mockups.
* Create a custom dialog Preference name it *SignOutDialogPreference.java* for Signout.
* Theme *entries* and *entryValues* should be **Dark and Light** and default values as *Dark*.

**Sample UI**:
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#settings-activity

### PR DESCRIPTION
**Pull request by YuganshT79**
Fixes #105 

## Description

Implemented the Settings Activity with all the necessary requirements
- **Switch** for enabling/disabling notifications
- Preference to change theme to - Dark / Light
- Sign out button and *Sign out* dialog

## Screenshots

**BEFORE**:
Not applicable

**AFTER**:
   
    

## Other changes (e.g. bug fixes, UI tweaks, refactors)
- Fixed redundant code in activity_user_profile.xml
- Added vector icon **ic_close.xml** 
- Added support dependency for preferences
- Fixed *colors/transparent*

### CODE REVIEW

**Comment by YuganshT79** [comment]
@sagarsrao It was specified in the design of the app to have an icon on the dialog box, should I remove it ?

**Comment by sagarsrao** [comment]
yes, please!

**Comment by YuganshT79** [comment]
Ok, I will just remove the Icon from dialog box and push the changes

**Comment by YuganshT79** [comment]
@sagarsrao Thanks 😄

**Comment by vansh1sh** [comment]
@YuganshT79 Thankyou for your contribution. We appreciate your work :)

**Pull request merged**
