### PR TITLE
Added the settings activity as per the mocks

### LINKED ISSUE #105: Settings Activity
**Complete By: 8th May 2018 EOD**

This is the settings activity of the QuizApp and it contains some basic settings.

**Requirements:**
* It must contain three items, check out the sample UI.
* Create a **SettingsActivity.java**.
* Create a *settings_app.xml* inside the *res/xml* folder and add the **PreferenceScreen** inside that activity and the respective items as shown in mockups.
* Create a custom dialog Preference name it *SignOutDialogPreference.java* for Signout.
* Theme *entries* and *entryValues* should be **Dark and Light** and default values as *Dark*.

**Sample UI**:
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#settings-activity

### PR DESCRIPTION
**Pull request by tavishjain**
Fixes #105 

## Description

This is the settings activity of the QuizApp and it contains some basic settings

## Screenshots

**BEFORE**:
[if applicable, insert screenshot here]

**AFTER**:
[insert screenshot here]

## Other changes (e.g. bug fixes, UI tweaks, refactors)

Also added the dialog box for log out

### CODE REVIEW

**Comment by tavishjain** [comment]
@imashwani that work is pending I know

**Comment by tavishjain** [comment]
Pls review the rest of it

**Comment by vansh1sh** [comment]
@tavishjain It seems you have not yet added the sign out dialog. Please complete the requirements.

**Comment by sagarsrao** [comment]
Tavish Jain:) We appreciate your time and contribution. We are closing this PR due to the following reasons
1. Every of your XML files have the hardcoded strings.it should be dynamically taken from styling resources.
2.PR is not containing any screenshots of the work you have done.
3. Files that you have pushed does have conflictions.
Please take this as a learning.

**Pull request closed without merging**
