### PR TITLE
feature-detailspage

### LINKED ISSUE #19: Get Details Page UI
Complete by: 19 April 2018 EOD.

- It is a one time screen after a user authenticates. 

The fields should include:
- Name
- Photo (Use an image from your google account OR select an avatar from a list)
- Slack Handle
- Select your track spinner.
- Email (Not editable, only Text view)
- Submit/Next Button

A sample UI :

### PR DESCRIPTION
**Pull request by SrikarNanduri**
Fixes #19 

## Description

Added Details Page UI

## Before & After Screenshots

**BEFORE**:
edit details

## Other changes (e.g. bug fixes, UI tweaks, refactors)

1. Added 2 simple xml files one for exiting screen `details_page_ui_edit.xml` and the other for after `screen detail_page_ui.xml`
2. Added an image resource `user_profile`.

### CODE REVIEW

**Comment by SrikarNanduri** [comment]
Done the changes as instructed, kindly let me know if there is anything i need to change.

**Comment by thayumaanavan** [comment]
@SrikarNanduri  First before creating PR, you need to comment on the issue #19 that you are working on it. we need only first screenshot layout not the 2nd one as this screen will be shown only after login. Please do below actions:
1. Add a comment in the issue page
2. Remove the 2nd screenshot layout

**Comment by thayumaanavan** [comment]
@SrikarNanduri Just comment now. Also, remove the other layout and gradle file change. You commit should have only the changes related to the issue.

**Comment by aditisoni8899** [comment]
@SrikarNanduri Thankyou for the contribution. Please don't be disheartened if your PR is not selected.  We appreciate your work. But as a team decision based on votes, we are selecting the best UI PRs.

Feedback from our side:
- Simple as compared to other PRs.
- Color combination could be better.

We're closing this PR. Looking forward to some more contributions from your side.

**Pull request closed without merging**
